dist: xenial
language: node_js
branches:
  only:
    - master
node_js:
  - "8.11"
addons:
  apt:
    packages:
      - libavahi-compat-libdnssd-dev xvfb libxtst6 libxss1 libgtk2.0-0 libnss3 libasound2 libgconf-2-4 lftp
services:
  - xvfb
cache:
  directories:
    - node_modules # NPM packages
install:
  - npm install
jobs:
  include:
    - stage: test
      script: npm run lint -- --max-warnings 0 &&
              npm run sass-lint -- --max-warnings 0 &&
              npm run test &&
              npm run build
      script: npm run build:ci &&
              xvfb-run --server-args="-screen 0 1440x900x24" -a npm run test:e2e:ci
      after_script: awk -v build_id="$TRAVIS_BUILD_ID" '{ print "mkdir -p /travis/" build_id }' | lftp -u $FTP_USER,$FTP_PASSWORD $FTP_HOST &&
                    find ./test -wholename "**/__diff_output__/*.png" -print | awk -v build_id="$TRAVIS_BUILD_ID" '{ print "put -O /travis/" build_id " " $0 }' | lftp -u $FTP_USER,$FTP_PASSWORD $FTP_HOST

