language: node_js
branches:
  only:
    - master
node_js:
  - "8.11"
cache:
  directories:
    - node_modules # NPM packages
before_install:
  - sudo apt-get update -q
  - sudo apt-get install libavahi-compat-libdnssd-dev -y
install:
  - npm install
jobs:
  include:
    - stage: test
      script: npm run lint -- --max-warnings 0 &&
              npm run sass-lint -- --max-warnings 0 &&
              npm run test &&
              npm run build
    - stage: regression
      script: npm run build:ci &&
              npm run test:e2e:ci
