language: node_js
branches:
  only:
    - master
node_js:
  - "8.11"

addons:
  apt:
    packages:
      - xvfb
cache:
  directories:
    - node_modules # NPM packages
before_install:
  - sudo apt-get update -q
  - sudo apt-get install libavahi-compat-libdnssd-dev -y
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
jobs:
  include:
    - stage: test
      script: npm run lint -- --max-warnings 0 &&
              npm run sass-lint -- --max-warnings 0 &&
              npm run test &&
              npm run build
      script: npm run build:ci &&
              npm run test:e2e:ci
