dist: xenial
language: node_js
branches:
  only:
    - master
node_js:
  - "12.8.0"
addons:
  apt:
    packages:
      - libavahi-compat-libdnssd-dev
services:
  - xvfb
cache:
  directories:
    - node_modules # NPM packages
    - integration-tests/.data # integration test downloads

install:
  - npm install
jobs:
  include:
    - stage: prepare cache
      script: node integration-tests/scripts/get-development-protocol.js
    - stage: test
      script: npm run lint -- --max-warnings 0 &&
        npm run sass-lint -- --max-warnings 0 &&
        npm run test &&
        npm run build
