version: '3'
services:
  sut:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
      - /app/www
    command: bash -c "npm install && npm run build:ci && xvfb-run --server-args=\"-screen 0 1024x768x24\" npm run test:e2e:ci"
