version: '3'
services:
  integration_tests:
    build: .
    shm_size: '512m'
    volumes:
      - ./scripts:/app/scripts
      - ./config:/app/config
      - ./public:/app/public
      - ./src:/app/src
      - ./integration-tests:/app/integration-tests
    command: bash -c "npm run build:ci && xvfb-run -a npm run test:integration:ci"
  update_snapshots:
    build: .
    shm_size: '512m'
    volumes:
      - ./scripts:/app/scripts
      - ./config:/app/config
      - ./public:/app/public
      - ./src:/app/src
      - ./integration-tests:/app/integration-tests
    command: bash -c "npm run build:ci && xvfb-run -a npm run test:integration:ci --updateSnapshot"
